title: "Stata Crash Course"
author: "Tom Günther"
copyright = '2025, Günther, Tom'

only_build_toc_files: true

launch_buttons:
  thebe: true

execute:
  execute_notebooks: "off"

html:
  baseurl: /stata-crashcourse